[package]
name    = "ars-fac"
version = "0.1.0"
edition = "2021"
resolver = "2"

[[bin]]
name    = "ars-fac"
path    = "src/main.rs"
harness = false

[dependencies]
esp-idf-svc = { version = "0.49", features = ["native"] }

[build-dependencies]
embuild = "0.32"

[profile.release]
opt-level = "s"

[profile.dev]
opt-level = "z"
debug     = true