# .cargo/config.toml
# ──────────────────────────────────────────────────────────────────────────────
# Xtensa ESP32-S3 target — butuh Rust fork dari Espressif
#   Setup: https://esp-rs.github.io/book/installation/index.html
#   $ espup install          (install toolchain + target)
#   $ . ~/export-esp.sh      (atau tambah ke shell profile)
# ──────────────────────────────────────────────────────────────────────────────

[target.xtensa-esp32s3-none-elf]
runner = "probe-rs run --chip esp32s3"

[build]
target = "xtensa-esp32s3-none-elf"

# build-std diperlukan untuk no_std tanpa std library
[unstable]
build-std = ["core"]
